In [15]:
import numpy as np
import pandas as pd
import datetime

In [3]:
stealing_df = pd.read_csv('combined.csv')

stealing_df.drop(columns=['Unnamed: 0'], inplace=True)

stealing_df.head()

,Start_Base,End_Base,Event,Respon_Pitcher,runner_id,runner_name,pitcher_id,pitcher_name,batter_id,batter_name,pitch_hand,credit,credit_id,homeScore,awayScore,inning,isTopInning,Date,Action,Base
0,1B,NaN,Caught Stealing 2B,NaN,545341,Randal Grichuk,643338,Chad Green,543760,Marcus Semien,R,Gary Sánchez,596142,2,2,7,True,2021-04-01,Caught,2B
1,1B,2B,Stolen Base 2B,NaN,643565,Mike Tauchman,605447,Jordan Romano,457803,Jay Bruce,R,Danny Jansen,643376,2,2,9,False,2021-04-01,Stolen,2B
2,2B,3B,Stolen Base 3B,NaN,643565,Mike Tauchman,605447,Jordan Romano,640449,Clint Frazier,R,Danny Jansen,643376,2,2,9,False,2021-04-01,Stolen,3B
3,1B,2B,Stolen Base 2B,NaN,666185,Dylan Carlson,489334,Craig Stammen,425877,Yadier Molina,R,Austin Nola,543592,3,6,4,True,2020-09-30,Stolen,2B
4,2B,3B,Stolen Base 3B,NaN,502054,Tommy Pham,650893,Génesis Cabrera,543592,Austin Nola,L,Yadier Molina,425877,4,6,6,False,2020-09-30,Stolen,3B

In [10]:
stealing_df['Date'] = pd.to_datetime(stealing_df['Date'])

In [11]:
runner_df = pd.read_csv('Runner_final/A.J._Pierzynski.csv')
runner_df['Date'] = pd.to_datetime(runner_df['Date'])
runner_df.head()

,Unnamed: 0,Start_Base,End_Base,Event,runner_id,runner_name,pitcher_id,pitcher_name,batter_id,batter_name,...,homeScore,awayScore,inning,isTopInning,Date,Action,Base,Year,Current_Year,Sprint
0,0,1B,2B,Stolen Base 2B,451594,Dexter Fowler,571946,Shelby Miller,592178,Kris Bryant,...,0,3,5,True,2015-07-19,Stolen,2B,2015,2016,26.9
1,1,1B,2B,Stolen Base 2B,624585,Jorge Soler,501593,Luis Avilán,458085,Chris Coghlan,...,0,3,7,True,2015-07-19,Stolen,2B,2015,2016,26.9
2,2,1B,2B,Stolen Base 2B,453568,Charlie Blackmon,571946,Shelby Miller,518934,DJ LeMahieu,...,1,0,3,False,2015-07-10,Stolen,2B,2015,2016,26.9
3,3,1B,NaN,Caught Stealing 2B,488681,Brandon Barnes,571946,Shelby Miller,444836,Aaron Laffey,...,3,0,4,False,2015-07-10,Caught,2B,2015,2016,26.9
4,4,1B,NaN,Caught Stealing 2B,572019,Ben Paulsen,571946,Shelby Miller,518614,Daniel Descalso,...,5,0,5,False,2015-07-10,Caught,2B,2015,2016,26.9

In [21]:
runner_df.columns

Index(['Unnamed: 0', 'Start_Base', 'End_Base', 'Event', 'runner_id',
       'runner_name', 'pitcher_id', 'pitcher_name', 'batter_id', 'batter_name',
       'pitch_hand', 'credit', 'credit_id', 'homeScore', 'awayScore', 'inning',
       'isTopInning', 'Date', 'Action', 'Base', 'Year', 'Current_Year',
       'Sprint'],
      dtype='object')

In [23]:
runner_df[['credit']]

             credit
0   A.J. Pierzynski
1   A.J. Pierzynski
2   A.J. Pierzynski
3   A.J. Pierzynski
4   A.J. Pierzynski
5   A.J. Pierzynski
6   A.J. Pierzynski
7   A.J. Pierzynski
8   A.J. Pierzynski
9   A.J. Pierzynski
10  A.J. Pierzynski
11  A.J. Pierzynski
12  A.J. Pierzynski
13  A.J. Pierzynski
14  A.J. Pierzynski
15  A.J. Pierzynski
16  A.J. Pierzynski
17  A.J. Pierzynski
18  A.J. Pierzynski
19  A.J. Pierzynski
20  A.J. Pierzynski
21  A.J. Pierzynski
22  A.J. Pierzynski
23  A.J. Pierzynski
24  A.J. Pierzynski
25  A.J. Pierzynski
26  A.J. Pierzynski
27  A.J. Pierzynski
28  A.J. Pierzynski
29  A.J. Pierzynski
30  A.J. Pierzynski
31  A.J. Pierzynski
32  A.J. Pierzynski
33  A.J. Pierzynski
34  A.J. Pierzynski
35  A.J. Pierzynski
36  A.J. Pierzynski
37  A.J. Pierzynski
38  A.J. Pierzynski
39  A.J. Pierzynski
40  A.J. Pierzynski
41  A.J. Pierzynski
42  A.J. Pierzynski
43  A.J. Pierzynski
44  A.J. Pierzynski
45  A.J. Pierzynski
46  A.J. Pierzynski
47  A.J. Pierzynski
48  A.J. Pierzynski
49  A.J. Pierzynski
50  A.J. Pierzynski
51  A.J. Pierzynski
52  A.J. Pierzynski
53  A.J. Pierzynski

In [22]:
runner_df['Start_Base_num']  = runner_df['Start_Base'].apply(lambda x: 1 if x == '1B' else (2 if x == '2B' else 3))

In [20]:
runner_df.loc[(runner_df['Date'] <= pd.to_datetime('2015-07-10'))].head(30)

,Unnamed: 0,Start_Base,End_Base,Event,runner_id,runner_name,pitcher_id,pitcher_name,batter_id,batter_name,...,homeScore,awayScore,inning,isTopInning,Date,Action,Base,Year,Current_Year,Sprint
2,2,1B,2B,Stolen Base 2B,453568,Charlie Blackmon,571946,Shelby Miller,518934,DJ LeMahieu,...,1,0,3,False,2015-07-10,Stolen,2B,2015,2016,26.9
3,3,1B,NaN,Caught Stealing 2B,488681,Brandon Barnes,571946,Shelby Miller,444836,Aaron Laffey,...,3,0,4,False,2015-07-10,Caught,2B,2015,2016,26.9
4,4,1B,NaN,Caught Stealing 2B,572019,Ben Paulsen,571946,Shelby Miller,518614,Daniel Descalso,...,5,0,5,False,2015-07-10,Caught,2B,2015,2016,26.9
5,5,1B,2B,Stolen Base 2B,453568,Charlie Blackmon,544365,Manny Bañuelos,518934,DJ LeMahieu,...,5,3,6,False,2015-07-10,Stolen,2B,2015,2016,26.9
6,6,1B,2B,Stolen Base 2B,516416,Jean Segura,605538,Matt Wisler,455117,Martín Maldonado,...,1,4,5,False,2015-07-06,Stolen,2B,2015,2016,26.9
7,7,1B,2B,Stolen Base 2B,514917,César Hernández,571946,Shelby Miller,596748,Maikel Franco,...,0,0,3,True,2015-07-05,Stolen,2B,2015,2016,26.9
8,8,2B,NaN,Caught Stealing 3B,546318,Odúbel Herrera,571946,Shelby Miller,514917,César Hernández,...,0,0,5,True,2015-07-05,Caught,3B,2015,2016,26.9
9,9,1B,2B,Stolen Base 2B,514917,César Hernández,571946,Shelby Miller,429667,Ryan Howard,...,0,0,5,True,2015-07-05,Stolen,2B,2015,2016,26.9
10,10,1B,2B,Stolen Base 2B,520471,Freddy Galvis,502010,Jake Brigham,502126,Domonic Brown,...,0,4,10,True,2015-07-05,Stolen,2B,2015,2016,26.9
11,11,1B,2B,Stolen Base 2B,452655,Denard Span,544365,Manny Bañuelos,488862,Yunel Escobar,...,0,0,1,True,2015-07-02,Stolen,2B,2015,2016,26.9
12,12,1B,2B,Stolen Base 2B,452655,Denard Span,544365,Manny Bañuelos,457787,Danny Espinosa,...,1,0,6,True,2015-07-02,Stolen,2B,2015,2016,26.9
13,13,1B,2B,Stolen Base 2B,452655,Denard Span,571946,Shelby Miller,457787,Danny Espinosa,...,0,5,4,True,2015-06-30,Stolen,2B,2015,2016,26.9
14,14,1B,2B,Stolen Base 2B,628356,Jung Ho Kang,622072,Alex Wood,516782,Starling Marte,...,0,0,1,False,2015-06-28,Stolen,2B,2015,2016,26.9
15,15,1B,NaN,Caught Stealing 2B,474568,Jordy Mercer,622072,Alex Wood,446481,Sean Rodríguez,...,0,1,5,False,2015-06-28,Caught,2B,2015,2016,26.9
16,16,3B,score,Stolen Base Home,516782,Starling Marte,527054,Julio Teheran,474568,Jordy Mercer,...,6,1,5,False,2015-06-27,Stolen,Home,2015,2016,26.9
17,17,1B,2B,Stolen Base 2B,476883,Pedro Alvarez,527054,Julio Teheran,474568,Jordy Mercer,...,6,1,5,False,2015-06-27,Stolen,2B,2015,2016,26.9
18,18,2B,3B,Stolen Base 3B,572191,Michael A. Taylor,622072,Alex Wood,544931,Stephen Strasburg,...,1,0,3,False,2015-06-23,Stolen,3B,2015,2016,26.9
19,19,1B,2B,Stolen Base 2B,457477,Alejandro De Aza,571946,Shelby Miller,543768,Travis Shaw,...,0,1,5,True,2015-06-18,Stolen,2B,2015,2016,26.9
20,20,1B,2B,Stolen Base 2B,571553,Darrell Ceciliani,430911,David Aardsma,501571,Juan Lagares,...,4,3,7,False,2015-06-12,Stolen,2B,2015,2016,26.9
21,21,1B,2B,Stolen Base 2B,461416,Will Venable,571946,Shelby Miller,457708,Justin Upton,...,0,1,3,True,2015-06-08,Stolen,2B,2015,2016,26.9
22,22,1B,2B,Stolen Base 2B,457708,Justin Upton,592533,Cody Martin,461314,Matt Kemp,...,3,4,11,True,2015-06-08,Stolen,2B,2015,2016,26.9
23,23,2B,3B,Stolen Base 3B,461314,Matt Kemp,501593,Luis Avilán,506560,Alexi Amarista,...,3,5,11,True,2015-06-08,Stolen,3B,2015,2016,26.9
24,24,1B,2B,Stolen Base 2B,516782,Starling Marte,622072,Alex Wood,628356,Jung Ho Kang,...,0,0,1,True,2015-06-07,Stolen,2B,2015,2016,26.9
25,25,1B,2B,Stolen Base 2B,570256,Gregory Polanco,554234,Williams Pérez,516782,Starling Marte,...,2,1,3,True,2015-06-05,Stolen,2B,2015,2016,26.9
26,26,1B,2B,Stolen Base 2B,570256,Gregory Polanco,502239,Trevor Cahill,516782,Starling Marte,...,5,8,8,True,2015-06-05,Stolen,2B,2015,2016,26.9
27,27,1B,2B,Stolen Base 2B,542255,Ender Inciarte,571946,Shelby Miller,572041,AJ Pollock,...,4,1,4,False,2015-06-02,Stolen,2B,2015,2016,26.9
28,28,1B,2B,Stolen Base 2B,542255,Ender Inciarte,434665,Nick Masset,572041,AJ Pollock,...,4,6,6,False,2015-06-02,Stolen,2B,2015,2016,26.9
29,29,1B,2B,Stolen Base 2B,572041,AJ Pollock,622072,Alex Wood,502671,Paul Goldschmidt,...,0,0,1,False,2015-06-01,Stolen,2B,2015,2016,26.9
30,30,1B,2B,Stolen Base 2B,605412,Joe Panik,462382,Jim Johnson,457763,Buster Posey,...,3,1,8,False,2015-05-29,Stolen,2B,2015,2016,26.9
31,31,1B,2B,Stolen Base 2B,543063,Brandon Crawford,462382,Jim Johnson,434636,Ángel Pagán,...,4,1,8,False,2015-05-29,Stolen,2B,2015,2016,26.9

In [ ]:
for row, i in stealing_df.iterrows():
    catcher_id = i['creid_id']
    
    runner_id = i['pitcher_id']
    
    catcher_name = i['credit']
    
    runner_name = i['runner_name']
    
    date = i['Date']
    
    runner_df = pd.read_csv(f'Runner_final/{runner_name}')
    
    catcher_df = pd.read_csv(f'Runner_final/{catcher_name}')
    
    runner_df.loc[runner_df['Date'] <= date]